# Generated by Django 4.1.3 on 2024-08-13 05:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_sale_expire_date_alter_sale_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='expire_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='sale',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sale',
            name='qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_amt',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
