# Generated by Django 4.1.3 on 2024-08-13 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_sale_expire_date_alter_sale_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='expire_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sale',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sale',
            name='qty',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_amt',
            field=models.FloatField(editable=False),
        ),
    ]
