# Generated by Django 4.1.3 on 2024-08-13 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_remove_product_total_purchases_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Your Company Name', max_length=255)),
                ('address_line_1', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(default='(555) 123-4567', max_length=20)),
                ('email', models.EmailField(default='info@yourcompany.com', max_length=254)),
            ],
        ),
    ]
